services:
- type: web
  name: knockout-whist
  runtime: docker
  repo: https://github.com/tech4bueno/knockout-whist
  plan: free
  region: frankfurt
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
